//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Please provide a User name",AllowEmptyStrings = false)]
        public string Username { get; set; }
       [Required(ErrorMessage ="Please provide A username",AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        [StringLength(50,MinimumLength = 8,ErrorMessage = "password must be 8 charter")]
        public string Password { get; set; }
        [Compare("Password",ErrorMessage = "Confirm password does not match")]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
       public string ConfirmPassword { get; set; }
        [Required(ErrorMessage = "please provide name",AllowEmptyStrings = false)]
        public string Name { get; set; }
              [Required(ErrorMessage = "Please provide a Email", AllowEmptyStrings = false)]
        public string Email { get; set; }
    }
}
